language: android
jdk:
  - oraclejdk8
android:
  components:

# Defaults  
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    
# Extras
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

  licenses:
    - '.+'

# Setup JAVA env for components
before_install:
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME

# Default Gradle Test
script:
  - ./gradlew clean assemble || ./gradlew clean assemble
#   - ./gradlew build connectedCheck

# Fix Cache
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Notifications
notifications:
  email:
    recipients:
      - brandonschabell@gmail.com
    on_success: [change]
    on_failure: [always]
